"""Generate everything that tells a model how to write Scenet.

One generator, three destinations, all from the same sources:

    src/scenet/scenet-spec.md     the spec pack, packaged for the MCP server's get_spec
    skills/scenet/references/     the same parts as separate files, for an agent skill
    skills/scenet/assets/gallery/ the gallery, byte for byte
    site/scenet-spec.md           the spec pack, at a stable URL         (site build only)
    site/llms.txt                 an index for retrieval, per llmstxt.org (site build only)

The first three are committed, because neither an installed wheel nor a copied skill
folder can read `docs/`. `tests/test_spec_pack.py` regenerates them and fails on any
difference, so a committed copy cannot go stale -- the same arrangement that keeps the
editor's JSON Schemas honest.

Nothing here carries a version number or a date. Either would make every release, or
every day, a reason for the committed copies to differ from a fresh build.

Run from the repository root after changing any source document:

    uv run python scripts/build_spec.py           # rewrite the committed copies
    uv run python scripts/build_spec.py --check   # exit 1 if any is stale
"""

import argparse
import json
import posixpath
import re
import sys
from pathlib import Path

import yaml

from scenet import CastMember, default_library
from scenet.diagnostics import RULE_NAMESPACE, RULES
from scenet.schema import panel_schema
from scenet.spec_pack import MARKER, RESOURCE, SPEC_PARTS

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
GALLERY = ROOT / "examples" / "gallery"
PACKAGED = ROOT / "src" / "scenet" / RESOURCE
SKILL = ROOT / "skills" / "scenet"

#: Where the documentation is published. Relative links are rewritten against this,
#: because `shot_types.md` means nothing once the pack has left the repository.
SITE = "https://creatoan.github.io/scenet"

#: Directories this script owns outright. Anything in them it did not generate is a
#: leftover -- an example deleted from the gallery, say -- and is removed.
GENERATED_DIRECTORIES = (SKILL / "references", SKILL / "assets")

#: Parts taken from a documentation page, by path under `docs/`.
DOCUMENT_PARTS = {
    "language": "reference/language.md",
    "shot-types": "reference/shot_types.md",
    "comic-script": "howto/write_a_comic_script.md",
}

#: Parts the skill carries as reference files. The preamble is what SKILL.md itself
#: says, the schema is for tools rather than for reading, and the gallery is an asset.
SKILL_REFERENCES = ("language", "shot-types", "comic-script", "characters", "diagnostics")

#: The documentation pages `llms.txt` lists, with what each is for. The titles are read
#: from the pages themselves, so a renamed page cannot leave a stale title behind.
LLMS_DOCUMENTS = {
    "reference/language": "every construct of the YAML language",
    "howto/write_a_comic_script": "the comic-script format, which a chat model can write unaided",
    "reference/shot_types": "normative: what each camera shot frames",
    "reference/cli": "`scenet build`, `scenet check` and `scenet mcp`",
    "reference/mcp": "the MCP server's tools",
    "howto/drive_from_a_model": "using Scenet from a chat app, an agent or an MCP client",
    "tutorial/first_panel": "one panel built from nothing",
}

LLMS_OPTIONAL = {
    "explanation/design_decisions": "why the language is shaped the way it is",
    "explanation/prior_art": "what this draws on, and what was rejected",
}

GENERATED_NOTICE = (
    "<!-- Generated by scripts/build_spec.py from {source}. "
    "Edit the source and regenerate; do not edit this file. -->\n\n"
)

LINK = re.compile(r"\]\(([^)\s]+)\)")


def _absolute_links(text: str, page: str) -> str:
    """Rewrite every relative link in a documentation page to its published URL.

    Args:
        text: The page's Markdown.
        page: Its path under `docs/`, such as `reference/language.md`.

    Returns:
        The same Markdown, with `shot_types.md#x` become `<site>/reference/shot_types.html#x`.
        Links with a scheme, and same-page anchors, are left alone: an anchor still
        resolves inside the pack, because the heading it names is in there too.
    """

    def rewrite(match: re.Match[str]) -> str:
        target = match.group(1)
        if re.match(r"[a-z][a-z0-9+.-]*:|#", target):
            return match.group(0)
        path, _, anchor = target.partition("#")
        resolved = posixpath.normpath(posixpath.join(posixpath.dirname(page), path))
        if resolved.endswith(".md"):
            resolved = resolved.removesuffix(".md") + ".html"
        return f"]({SITE}/{resolved}{'#' + anchor if anchor else ''})"

    return LINK.sub(rewrite, text)


def _title(page: str) -> str:
    """The first top-level heading of a documentation page."""
    for line in (DOCS / f"{page}.md").read_text(encoding="utf-8").splitlines():
        if line.startswith("# "):
            return line.removeprefix("# ").strip()
    raise ValueError(f"docs/{page}.md has no top-level heading")


def _fence(content: str, language: str) -> str:
    """A fenced block long enough that nothing inside it can close it early."""
    longest = max((len(run) for run in re.findall(r"`{3,}", content)), default=2)
    ticks = "`" * (longest + 1)
    return f"{ticks}{language}\n{content.rstrip()}\n{ticks}\n"


def _gallery_entries() -> list[dict[str, str]]:
    manifest = yaml.safe_load((GALLERY / "manifest.yaml").read_text(encoding="utf-8"))
    return manifest["examples"]


def _preamble() -> str:
    puppets = ", ".join(f"`{name}`" for name in default_library().names())
    contents = "\n".join(f"- `{name}` — {description}" for name, description in SPEC_PARTS.items())
    return f"""\
# Scenet specification pack

Everything needed to write a Scenet panel, in one file. Published at
<{SITE}/scenet-spec.md> and regenerated from the project's own sources on every build,
so it describes the language the compiler actually accepts.

> This project is deliberately AI-generated: the compiler, its documentation and this
> file are almost entirely written by AI under human direction and review. Treat it as
> an experiment first and a tool second.

## What Scenet is

Scenet compiles a *semantic* description of a comic panel — who is in it, how they
relate, what they say — into SVG. It is a deterministic compiler built on constraint
solving and geometry. **No generative image model is involved.** The same document
always produces the same picture, byte for byte.

You describe the panel; the compiler decides every coordinate. **Never write
coordinates**, pixel positions for figures, or balloon placements: the language has
nowhere to put them, and unknown keys are rejected.

## Two ways to write a panel

1. **YAML** — `*.panel.yaml` for one panel, `*.scene.yaml` for a sequence. The whole
   language; see the `language` part.
2. **Comic script** — `*.script`. The format comic writers already use: `PANEL 1`,
   `@shot:`, a character cue, the dialogue under it, with a short YAML front matter
   declaring the cast. See the `comic-script` part.

**If you cannot run code** — a chat app, NotebookLM — write a comic script. It is the
closest thing to what you would write anyway, and the person you are helping compiles
it with one command: `scenet build panel.script`.

## The loop

1. Write the document.
2. Run `scenet check FILE`. It reports every fault at once, each with a rule id such as
   `{RULE_NAMESPACE}/unknown-actor`, a line and column, and what to do about it. Add
   `--format sarif` for a machine-readable report.
3. Fix what it reports and check again, until it prints `ok`.
4. Run `scenet build FILE` to write the SVG.

With the Scenet MCP server connected, the `validate`, `compile` and `render` tools do
the same without a shell.

**A schema-valid document is not yet a valid one.** No JSON Schema can catch the faults
that matter most — an actor id that is not in `cast`, a `left_of` ordering that loops —
so always check.

## The mistakes generators make most

- **Every actor id used in `staging` or `script` must be a key of `cast`.** Ids are
  case-sensitive.
- **`reference` names a puppet in the library.** The shipped puppets are {puppets}.
  `pose` and `expression` must be names that puppet declares; see the `characters`
  part. Do not invent them.
- **Two figures need a left-to-right order**, from `at:` or from an explicit
  `a left_of b`. There is no unordered "beside".
- **Script order is reading order.** A balloon may never sit above-and-left of the one
  before it, so write the lines in the order they are read.
- **Shots are named** — `medium_shot`, `close_up` — never a percentage of the panel.
- **Prose in a comic script is kept and never interpreted.** Staging that matters goes
  in the front matter.

## Contents

{contents}
"""


def _default(field: str) -> str:
    """A cast member's default for one field, read from the model rather than restated."""
    return str(CastMember.model_fields[field].default)


def _characters() -> str:
    library = default_library()
    rows = []
    for name in library.names():
        puppet = library.get(name)
        poses = ", ".join(f"`{pose}`" for pose in sorted(puppet.poses))
        expressions = ", ".join(f"`{expression}`" for expression in sorted(puppet.expressions))
        rows.append(f"| `{name}` | {puppet.heads_tall:.1f} | {poses} | {expressions} |")
    return (
        "# Characters\n\n"
        "The puppets shipped with Scenet. A cast member's `reference` names one of these, "
        "and its `pose` and `expression` must be names that puppet declares. `pose` "
        f"defaults to `{_default('pose')}` and `expression` to `{_default('expression')}`.\n\n"
        "| Puppet | Heads tall | Poses | Expressions |\n"
        "|---|---|---|---|\n" + "\n".join(rows) + "\n\n"
        "One puppet may appear several times in a panel under different actor ids. Your "
        "own puppets are described in "
        f"[the asset contract]({SITE}/reference/asset_contract.html).\n"
    )


def _diagnostics() -> str:
    entries = "\n\n".join(
        f"### `{RULE_NAMESPACE}/{name}`\n\n{rule.summary}. {rule.description}\n\n"
        f"**Fix:** {rule.help}"
        for name, rule in sorted(RULES.items())
    )
    return (
        "# Diagnostics\n\n"
        "Every rule `scenet check` can report. Each finding carries one of these ids, a "
        "message naming the offending construct, and a line and column. The ids are "
        "stable across releases.\n\n"
        f"{entries}\n"
    )


def _schema() -> str:
    document = json.dumps(panel_schema(), indent=2, sort_keys=True)
    return (
        "# JSON Schema\n\n"
        "The schema for a single-panel YAML document, generated from the compiler's own "
        "models. It describes the syntax people write, including staging sentences such "
        "as `alice left_of bob`. The multi-panel scene schema is at "
        f"<{SITE}/schemas/scene.schema.json>.\n\n"
        "Conforming to it is necessary, not sufficient: see the note on schema validity "
        "in the preamble.\n\n" + _fence(document, "json")
    )


def _gallery() -> str:
    sections = []
    for entry in _gallery_entries():
        path = GALLERY / entry["file"]
        language = "text" if path.suffix == ".script" else "yaml"
        source = path.read_text(encoding="utf-8")
        sections.append(f"## {entry['title']}\n\n`{entry['file']}`\n\n{_fence(source, language)}")
    return (
        "# Gallery\n\n"
        "Every example the playground offers, in the order it offers them. The test suite "
        "compiles each one, so all of them are known to work.\n\n" + "\n".join(sections)
    )


def parts() -> dict[str, str]:
    """Every part of the pack, in order, each ending in exactly one newline."""
    built = {
        "preamble": _preamble(),
        **{
            name: _absolute_links((DOCS / page).read_text(encoding="utf-8"), page)
            for name, page in DOCUMENT_PARTS.items()
        },
        "characters": _characters(),
        "diagnostics": _diagnostics(),
        "schema": _schema(),
        "gallery": _gallery(),
    }
    return {name: built[name].rstrip("\n") + "\n" for name in SPEC_PARTS}


def spec_pack() -> str:
    """The whole spec pack, as committed and as published."""
    body = "\n".join(f"{MARKER.format(name=name)}\n{text}" for name, text in parts().items())
    return GENERATED_NOTICE.format(source="docs/, examples/gallery/ and the package") + body


def llms_txt() -> str:
    """An index of the documentation, in the shape https://llmstxt.org proposes."""

    def links(pages: dict[str, str]) -> str:
        return "\n".join(
            f"- [{_title(page)}]({SITE}/{page}.html): {note}" for page, note in pages.items()
        )

    return f"""\
# Scenet

> A compiler that turns a semantic description of a comic panel — who is in it, how
> they relate, what they say — into SVG. Deterministic constraint solving and
> geometry; no generative image model is involved.

This file follows llms.txt, a community convention with no standards body behind it;
it is a distribution format, not a protocol. The project is deliberately AI-generated.
To write a panel, read the spec pack: it holds the language, the comic-script format,
the characters, the diagnostics, the JSON Schema and every example in one file.

## Specification

- [Spec pack]({SITE}/scenet-spec.md): everything needed to write a panel, in one file
- [Panel JSON Schema]({SITE}/schemas/panel.schema.json): a single-panel YAML document
- [Scene JSON Schema]({SITE}/schemas/scene.schema.json): a multi-panel YAML document

## Documentation

{links(LLMS_DOCUMENTS)}

## Optional

{links(LLMS_OPTIONAL)}
- [Playground]({SITE}/playground/): the compiler running in a browser
- [Source](https://github.com/creatoan/scenet): the repository
"""


def skill_files() -> dict[Path, bytes]:
    """The generated half of the skill folder. `SKILL.md` itself is written by hand."""
    built = parts()
    sources = {
        **{name: f"docs/{page}" for name, page in DOCUMENT_PARTS.items()},
        "characters": "the shipped puppet library",
        "diagnostics": "scenet.diagnostics.RULES",
    }
    files: dict[Path, bytes] = {
        SKILL / "references" / f"{name}.md": (
            GENERATED_NOTICE.format(source=sources[name]) + built[name]
        ).encode("utf-8")
        for name in SKILL_REFERENCES
    }
    gallery = SKILL / "assets" / "gallery"
    files[gallery / "manifest.yaml"] = (GALLERY / "manifest.yaml").read_bytes()
    for entry in _gallery_entries():
        files[gallery / entry["file"]] = (GALLERY / entry["file"]).read_bytes()
    return files


def committed_files() -> dict[Path, bytes]:
    """Every generated file that lives in the repository, with its expected content."""
    return {PACKAGED: spec_pack().encode("utf-8"), **skill_files()}


def write_site_files(site: Path) -> None:
    """Write the two files only the published site carries.

    Args:
        site: The assembled site directory; both files land at its root.
    """
    site.mkdir(parents=True, exist_ok=True)
    (site / "scenet-spec.md").write_text(spec_pack(), encoding="utf-8", newline="\n")
    (site / "llms.txt").write_text(llms_txt(), encoding="utf-8", newline="\n")


def _stale() -> list[Path]:
    expected = committed_files()
    stale = [
        path
        for path, content in expected.items()
        if not path.exists() or path.read_bytes() != content
    ]
    for directory in GENERATED_DIRECTORIES:
        if directory.exists():
            stale.extend(
                path
                for path in sorted(directory.rglob("*"))
                if path.is_file() and path not in expected
            )
    return stale


def main() -> int:
    """Rewrite the committed copies, or with `--check` report whether any is stale."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check", action="store_true", help="report stale files instead of rewriting them"
    )
    args = parser.parse_args()

    stale = _stale()
    if args.check:
        for path in stale:
            print(f"stale: {path.relative_to(ROOT)}", file=sys.stderr)
        return 1 if stale else 0

    expected = committed_files()
    for path in stale:
        if path in expected:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(expected[path])
            print(f"wrote {path.relative_to(ROOT)}")
        else:
            path.unlink()
            print(f"removed {path.relative_to(ROOT)}")
    if not stale:
        print("everything is current")
    return 0


if __name__ == "__main__":
    sys.exit(main())
